image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build and run Spring PetClinic
    init: ./mvnw package -DskipTests
    command: ./mvnw spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - github.copilot
